# 服务器配置
server:
  port: 8080

spring:
  # 数据库配置(来源数据: 谁要跟别人对比数据)
  source-datasource:
    jdbc-url: jdbc:mysql://10.41.224.105:10000/test
    username: root
    password: 9784!2d155#74aea
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 数据库配置(目标数据: 要跟谁对比)
  target-datasource:
    jdbc-url: jdbc:mysql://10.41.224.71:3306/ssm
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



logging:
  level:
    root: warn
    com.mysql.diff: debug